shared:
  seq_len: &seq_len 48
  pred_len: &pred_len 24
  criterion: &criterion "MSE"

preprocessing:
  scaler: "standard"
  scaler_kwargs: {}
  imputer: "iterative"
  imputer_kwargs: {max_iter: 20}
  mice_estimator: "ridge"
  mice_estimator_kwargs: {alpha: 10}
  indicator_kwargs: {}
  scale_columns: 
    - "trend"
    - "workload_intensity"
    - 'promotion_intensity'
    - 'maintenance_known'
  simple_impute_columns:
    - staffing_forecast
  other_impute_columns:
    - "demand_forecast"
    - 'upstream_quality_forecast'
    - 'shock_risk'
    - 'unit_reliability_forecast'
    - 'queue_pressure_forecast'
    - 'network_pressure_forecast'
    - 'event_load_forecast'
    - 'service_irregularity_risk_forecast'
    - 'throughput_disruption_risk_forecast'
  missing_indicator_columns: []
  #convert_to_categorical:
    #- "maintenance_known"
model: 
  hybrid: False
  model_name: xLSTMMixer
  model_kwargs: {seq_len: *seq_len, pred_len: *pred_len, kwargs: {xlstm_num_heads: 8, xlstm_num_blocks: 1, xlstm_dropout: 0.2}}
  
training: 
  optimizer: Adam
  optimizer_kwargs: {lr: 0.005, weight_decay: 0.0001}
  eta_min:  0.000001
  max_epochs: 30
  min_epochs: 5
  criterion: *criterion
  patience: 8
  batch_size: 128

data: 
  seq_len: *seq_len
  pred_len: *pred_len
  save_path: experiments/

# experiment with target loss only 